apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sensors
spec:
  selector:
    matchLabels:
      app: sensor
      version: "1"
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: sensor
        version: "1"
    spec:
      volumes:
        - name: "sensor-node-data"
          hostPath:
            path: "/var/lib/sensor-node"
            type: DirectoryOrCreate
      containers:
        - image: vismay3003/mock-sensor-node:v1
          name: sensor-node
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/data"
              name: "sensor-node-data"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c 
                - "find /data/edge_telemetry.db -mmin 1 | grep ."
            initialDelaySeconds: 5
            periodSeconds: 60
